[package]
name = "lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.14.0"
miette = "7.2.0"
thiserror = "1.0.59"

[dev-dependencies]
insta = "1.38.0"
miette = { features = ["fancy"] }
